version: '3.4'

services:
  restaurant.api:
    image: ${DOCKER_REGISTRY-}restaurantapi
    build:
      context: .
      dockerfile: src/Presentation/Restaurant.Api/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - wwwroot_data:/home/app/wwwroot

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  user_secrets:
  https_certs:
  wwwroot_data:
  sql_data:
