services:
  restaurant.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ApplicationDbContextConnection=Server=sqlserver;Database=RestaurantDb;User=sa;Password=Your_password123;TrustServerCertificate=true;encrypt=false
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
