global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Logging;
global using Restaurant.Application.Constants;
global using Restaurant.Application.Exceptions;
global using Restaurant.Application.Extensions;
global using Restaurant.Domain.Entities.Identity;
global using System.Security.Claims;